CREATE TABLE public.user 
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login varchar(100) not null, 
    password varchar(100) not null, 
    balance numeric(18,2) not null default 0 CHECK (balance >= 0),
    withdrawn numeric(18,2) not null default 0 CHECK (withdrawn >= 0),
    created timestamp not null default now(),
    CONSTRAINT constraint_user_login UNIQUE (login)
);