CREATE TABLE public.order
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid integer REFERENCES public.user (id),
    ordernumber varchar(100) not null, 
    status smallint not null, 
    accrual numeric(18,2) not null,
    created timestamp not null default now(),
    CONSTRAINT constraint_order_number UNIQUE (ordernumber)
);

CREATE TABLE public.withdraw
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid integer REFERENCES public.user (id),
    ordernumber varchar(100) not null, 
    sum numeric(18,2) not null, 
    created timestamp not null default now()
);